### ISSUE TITLE
Parsing does not fail on uneven number of quotation marks

### ISSUE THREAD

**Issue by faern** [emctague/comma#2]
If this is an issue or not depends on what the library is intended for I guess. But it behaves differently than for example bash when given an uneven number of quotes. The following test would currently fail to run:
```rust
#[test]
fn not_terminated_quote_block() {
    let result = Command::from_str("ls 'start end");
    assert!(result.is_err(), "Did not fail to parse uneven amount of quotation marks");
}
```

If I type `ls 'start end` in bash and hit enter it would just print `> ` and wait for me to finish my input. And if I actually force it to parse that string it will give me:
```
bash: unexpected EOF while looking for matching `''
```

## Expected behavior

Fail to parse input with an uneven number of quotation marks

**Comment by emctague** [comment]
I'll add a fix later today if I can, thank you!

**Comment by emctague** [comment]
Sorry I haven't gotten to it yet - I haven't worked with this code (or rust!) in a while, so my own source code is a bit confusing...

**Comment by emctague** [comment]
After 2 whole years I've finally picked up Rust a bit again, rewritten the library and fixed this issue in the process.
